

# For the Banner in the Home Page
banner:
- {image: 'banner01.jpg',
  prioridad: 'active',
  }
- {image: 'banner02.jpg',
  prioridad: '',
  }
- {image: 'banner03.jpg',
  prioridad: '',
  }
- {image: 'banner04.jpg',
  prioridad: '',
  }

Equipe:
- name: Laure Morel
  image: 'LM.jpg'
  description: Directrice du laboratoire ERPI
- name: Pascal Lhoste
  image: 'PL.jpg'  
  description: Directeur de l'ENSGSI
- name: Laurent Dupont
  image: 'LD.jpg'
  description: Responsable Scientifique du LF2L Ingénieur de Recherche ERPI / ENSGSI
- name: Giovanny Arbelaez
  image: 'GA.jpg'  
  description: Ingénieur de Recherche sur l'évaluation de l'acceptabilité des nouveaux produits
  linkedin: https://www.linkedin.com/in/gaarbelaez/
  google-scholar: https://scholar.google.fr/citations?user=qj178msAAAAJ&hl=en
  mendeley: https://www.mendeley.com/profiles/giovanny-arbelaez/ 
- name: Fabio Cruz
  image: 'FC.jpg'
  description: Ingénieur de Recherche sur le recyclage des plastiques pour l'impression 3D
  linkedin: https://www.linkedin.com/in/fabio-cruz/
  google-scholar: https://scholar.google.com/citations?user=8Cuoaf4AAAAJ&hl=es
  academia: https://univ-lorraine.academia.edu/FabioACruzS
  researchgate: https://www.researchgate.net/profile/Fabio_Cruz_Sanchez
  mendeley: https://www.mendeley.com/profiles/fabio-a-cruz-sanchez/  
- name: Gregory Dupont
  image: 'GD.jpg'  
  description: Responsable Technique et Matériaux
  

News:
- title: L'est Republicain
  image: 'News-1.jpg'
  description: Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.
- title: Pascal Lhoste
  image: 'News-2.jpg'  
  description: Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.
- title: Laurent Dupont
  image: 'News-3.jpg'
  description: Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.
- title: Giovanny Arbelaez
  image: 'News-4.jpg'  
  description: Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.
- title: Fabio Cruz
  image: 'News-5.jpg'
  description: Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.
- title: Gregory Dupont
  image: 'News-6.jpg'
  description: Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.

Partenaires:
- title: LorNTech
  image: 'LorNtech.jpg'
  url: http://www.lorntech.eu/
- title: Technopole Renaissance
  image: 'Technopole-Renaissance.jpg'  
  url: ''
- title: French-Tech
  image: 'French-Tech.jpg'
  url: http://www.lafrenchtech.com/
- title: Metropole du Grand Nancy
  image: 'MGN.PNG'  
  url: www.grandnancy.eu/
- title: ENEDIS
  image: 'ENEDIS.jpg'
  url: http://www.enedis.fr/
- title: EDF
  image: 'EDF.jpg'
  url: https://particulier.edf.fr/fr/accueil.html
- title: Université de Lorraine
  image: 'UL.jpg'
  url: http://www.univ-lorraine.fr/
- title: Lorraine INP
  image: 'INP.jpg'
  url: http://www.lorraine-inp.fr/
- title: F2I-UIMM
  image: 'F2I-UIMM.png'
  url: http://www.fonds-f2i.fr/







