#-------------------------------
# General Site Settings

title: Green FabLab
description: Creating a local recycling system would open up new opportunities for the circular economy
email: fabio-alberto.cruz-sanchez@univ-lorraine.fr

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Accueil, url: '#our-vision'}
- {name: Concept, url: '#research'}
- {name: Communauté, url: '#students'}
- {name: Lieu & Equipement, url: 'resources'}
- {name: Info pratiques, url: '#contact'}
#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Travis specializes in making things** for human people.
  Most of the things he makes are [digital interfaces](http://travisneilson.com){:target="_blank"},
  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making codes happen.


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: Standard Protocol for OS 3D Printers, description: "Experimental protocol of geometrical performance evaluation in order to characterise OS 3D printers in a robust manner.", folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Polymer Recycling Methodology, description: "General methodology to evaluate the recyclability of polymers used as feedstock for 3D printing machines",  folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Distributed Recycling, description: "",  folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Logistic Distributed Recycling,  description: "", folder: 'proj-4', file: 'work/proj-4.html'}
# - {name: Recycling in AM - Review, folder: 'proj-5', file: 'work/proj-5.html'}
# - {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
# - {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
# - {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:

- {avatar: 'Romain.jpg',
  name: 'Romain SCHILDKNECHT',
  title: 'Engineer',
  quote: '<p>I enjoyed participating in the Green FabLab project because it helps to create a short consumer circuit by discovering the plastic filament extrusion process. We worked on the use of the Xcalibur extruder. It is an easy to use machine but with many parameters. However it was a real pleasure to work in the laboratory with teams of different horizons and cultures.</p>',
  logo: 'logo-CESI.jpg'}
- {avatar: 'Alexis.jpg',
  name: 'Alexis SCHNELL',
  title: 'Engineer',
  quote: '<p>I liked the field of study in FabLab. Recycle, upgrade and extrude plastic material is very important for the world. Using equiments in Fablab was very interesting. I learned to use several equiments and I could to contribute to the advencement of the FabLab. I liked the working atmosphere and I would like to thanks all the members of the team for this internship.</p>',
  logo: 'logo-CESI.jpg'}
- {avatar: 'Santiago.jpg',
  name: 'Santiago REVORI',
  title: 'Universidad Nacional de Mar del Plata',
  quote: '<p>From the last five months, we worked with a team of three people with a extruder machine situated in the Lorraine FabLiving Lab. First of all, we learned how to use the 3D printing machines and also the scanner. After that we spent the rest of the time working in the extruder who provides the material for the printers. We learned how to do the filaments and also did a tutorial to show to everyone how to use it. For that, we made differents test and solved several problems that we found during this process.</p>',
  logo: 'logo-Mar-del-Plata.png'}
- {avatar: 'Women.png',
  name: 'Someone from Italy?',
  title: 'Master Recherche MIDI.',
  quote: '<p><strong>Say something nice of us..</strong> </p>',
  logo: 'logo-TORINO.png'}
- {avatar: 'Women.png',
  name: 'Someone from UNCUYO?',
  title: 'Engineer',
  quote: '<p><strong>Say something nice of us..</strong> </p>',
  logo: 'logo-UNCUYO.png'}




#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
